### ISSUE TITLE
icons are broken

### ISSUE THREAD

**Issue by SohnyBohny** [KaidanIM/Kaidan#252] opened 2018-05-14 07:45 UTC
## add contact icon
![image](https://user-images.githubusercontent.com/10254103/39984355-3db4eb26-575b-11e8-957d-b9ed3b7a3844.png)

## logout icon
![image](https://user-images.githubusercontent.com/10254103/39984338-2eeff36a-575b-11e8-98b7-c2a5d7370c26.png)

**Comment by JBBgameich** [comment] 2018-05-14 13:37
Which icon theme are you using? Breeze is tested and works fine. You could try building using qmake, which includes the Beezer icons into the binary. This is likely nothing we can solve, but your distribution or icon theme maintainer.

**Comment by SohnyBohny** [comment] 2018-05-14 16:01
I don't know exactly. How can I check this?
I did build it using qmake (on Antergos/Arch Linux). Is there any dependency I forgot to install?

**Comment by JBBgameich** [comment] 2018-05-14 16:03
If you fetched all the submodules before, you don't need to install any additional packages.

**Comment by SohnyBohny** [comment] 2018-05-14 16:09
Actually I was using cmake - I'm quite new to C++/QML 

By the way: which IDE are you using

**Comment by JBBgameich** [comment] 2018-05-14 16:14
Let's switch to the development channel kaidan@muc.kaidan.im for talk not related to the issue. For the channel you need to use a different XMPP client, Kaidan doesn't support this yet.

**Comment by JBBgameich** [comment] 2018-05-15 16:02
I can't reproduce this unfortunately and will close the issue for now. If there are any news on this, please just reopen it.

**Closed by JBBgameich** 2018-05-15 16:02 UTC
