### ISSUE TITLE
Connection failed or disconnected 13

### ISSUE THREAD

**Issue by mightyBroccoli** [KaidanIM/Kaidan#171] opened 2017-12-27 12:52 UTC
I get this error on trying to connect to my server.
Server : Prosody 0.10
Client : latest Kaidan source files
OS : Archlinux
Installed with AUR : https://aur.archlinux.org/packages/kaidan-git/

> [XML] [Outgoing] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> QXmlStreamWriter: writeCurrentToken() with invalid state.
> <stream:stream xmlns:n1="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" to="magicbroccoli.de" xml:lang="en" version="1.0
> [XML] [Incoming] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> <stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns:n1="jabber:client" xml:lang="en" from="magicbroccoli.de" id="3eeaf24a-0e07-496a-8809-26276dda925e" version="1.0"/>
> [XML] [Incoming] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> <stream:features xmlns:stream="http://etherx.jabber.org/streams" xmlns:n1="urn:ietf:params:xml:ns:xmpp-tls">
>     <n1:starttls>
>         <n1:required/>
>     </n1:starttls>
> </stream:features>
> [XML] [Outgoing] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> <n1:starttls xmlns:n1="urn:ietf:params:xml:ns:xmpp-tls"/>
> [XML] [Incoming] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> <n1:proceed xmlns:n1="urn:ietf:params:xml:ns:xmpp-tls"/>
> [Connection] Automatically accepting TLS certificate
> [Connection] Connection failed or disconnected 13

**Comment by JBBgameich** [comment] 2017-12-27 13:44
Maybe related to https://github.com/KaidanIM/Kaidan/issues/147

Are you using a debug or release build?

**Comment by LNJ2** [comment] 2017-12-27 15:41
Unfortunately this is a bug we don't understand at all, only release builds are affected, it's the same with both build systems. It has to do something with OpenSSL/GnuTLS.
If you want to use kaidan you'll have to use a debug build, for now.

**Comment by LNJ2** [comment] 2017-12-27 17:04
And just FYI: the AUR wasn't created by us, so we can't fix it.

**Comment by mightyBroccoli** [comment] 2018-01-07 14:17
I used this to build a new package but nevertheless I get the error from above. What am I doing wrong here?
```
 cd "$srcdir/kaidan/build"
  cmake -DCMAKE_BUILD_TYPE=Debug-DI18N=1 ..
  make
```

**Comment by LNJ2** [comment] 2018-01-07 14:18
If it's not a typo in your code example, there's a space missing inbetween `-DCMAKE_BUILD_TYPE=Debug` and `-DI18N=1`

**Comment by LNJ2** [comment] 2018-01-07 14:20
If this fixes your problem, we should close this issue, because it's a duplicate of #147

**Comment by LNJ2** [comment] 2018-01-13 15:11
I'll close this, as its a duplicate. @mightyBroccoli reopen if this is a really different problem. 🙂

**Closed** 2018-01-13 15:11 UTC
Labels: bug, duplicate

**Comment by LNJ2** [comment] 2018-03-18 09:43
This should be finally fixed, now: https://github.com/KaidanIM/Kaidan/commit/fb10738fca1960c120b5d4837d24622b1752cbd1
